// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var CakeSize$Variables = require("./CakeSize.bs.js");

var orders = [
  /* Half */1,
  /* Full */0,
  /* Half */1,
  /* Quater */2,
  /* Full */0,
  /* Quater */2,
  /* Half */1
];

var orderPrices = orders.map(CakeSize$Variables.getCakePrice);

console.log(orderPrices);

function add(accumulate, item) {
  return accumulate + item;
}

var numbers = [
  1,
  2,
  3,
  4,
  5,
  2,
  2,
  54,
  3,
  2,
  2,
  4,
  1
];

var totalPrice = orderPrices.reduce(add, 0.0);

console.log(totalPrice);

exports.orders = orders;
exports.orderPrices = orderPrices;
exports.add = add;
exports.numbers = numbers;
exports.totalPrice = totalPrice;
/* orderPrices Not a pure module */
