// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_math = require("bs-platform/lib/js/js_math.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Cake$Variables = require("./Cake.bs.js");

var cakeMessageArray = [
  "Happy Birthday",
  "Happy Anniversary",
  "Happy Death Day"
];

var cakeSizeChoiceArray = [
  /* Half */1,
  /* Full */0,
  /* Quarter */2
];

var cakeFrostingChoiceArray = [
  /* Vanilla */0,
  /* Chocolate */1
];

var cakeFillingChoiceArray = [
  /* Vanilla */0,
  /* Strawberry */4,
  /* Chocolate */1,
  /* Lemon */3,
  /* Raspberry */2
];

var cakeFlavorChoiceArray = [
  /* White */0,
  /* Yellow */1,
  /* Chocolate */2
];

var cakeLayersChoiceArray = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9
];

function getRandomChoice(arr) {
  return Caml_array.caml_array_get(arr, Js_math.random_int(0, arr.length));
}

function createRandomCake(param) {
  return {
          size: getRandomChoice(cakeSizeChoiceArray),
          flavor: getRandomChoice(cakeFlavorChoiceArray),
          frosting: getRandomChoice(cakeFrostingChoiceArray),
          layers: getRandomChoice(cakeLayersChoiceArray),
          filling: getRandomChoice(cakeFillingChoiceArray),
          message: getRandomChoice(cakeMessageArray)
        };
}

var theCake = createRandomCake(/* () */0);

var cakeString = Cake$Variables.cakeToString(theCake);

console.log(cakeString);

exports.cakeMessageArray = cakeMessageArray;
exports.cakeSizeChoiceArray = cakeSizeChoiceArray;
exports.cakeFrostingChoiceArray = cakeFrostingChoiceArray;
exports.cakeFillingChoiceArray = cakeFillingChoiceArray;
exports.cakeFlavorChoiceArray = cakeFlavorChoiceArray;
exports.cakeLayersChoiceArray = cakeLayersChoiceArray;
exports.getRandomChoice = getRandomChoice;
exports.createRandomCake = createRandomCake;
exports.theCake = theCake;
exports.cakeString = cakeString;
/* theCake Not a pure module */
