// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function quad(a, b, c) {
  console.log(a.toString() + ("x\u00b2 + " + (b.toString() + ("x + " + c.toString()))));
  var distcriment = b * b - 4.0 * a * c;
  if (distcriment < 0.0) {
    console.log("No real roots");
    return /* () */0;
  } else if (distcriment === 0.0) {
    var root = -b / (2.0 * a);
    console.log("Single root is ", root);
    return /* () */0;
  } else {
    var root1 = -b + Math.sqrt(distcriment) / (2.0 * a);
    var root2 = -b - Math.sqrt(distcriment) / (2.0 * a);
    console.log("Root1 is ", root1, "Root2 is ", root2);
    return /* () */0;
  }
}

quad(2.0, 3.0, -20.0);

exports.quad = quad;
/*  Not a pure module */
