// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var CakeSize$Variables = require("./CakeSize.bs.js");

function getLowerPrice(size) {
  return 0.99 * CakeSize$Variables.getCakePrice(size);
}

console.log(0.99 * CakeSize$Variables.getCakePrice(/* Half */1));

var myCake = /* Half */1;

exports.myCake = myCake;
exports.getLowerPrice = getLowerPrice;
/*  Not a pure module */
